### PR TITLE
Expand README to clarify testing purposes.

### PR DESCRIPTION
**Pull request by fnicolini**
Documentation is important!!

### CODE REVIEW

**Comment by dcasella** [comment]
@Jolsty please review.

**Comment by fnicolini** [comment]
> 
> 
> Looking good.
> The only thing I would change is the title "Prove". It's not in english!

Thanks for the suggestion @Jolsty, it's now fixed.

**Comment by dcasella** [comment]
@Alberto1598 Review please?

**Comment by dcasella** [comment]
> 
> 
>     * [x]  LGTM.

* [x] LGBT.

**Comment by Alberto1598** [comment]
Apes. @dcasella  Why the fuck you autolike your shitty cringe comments?

**Pull request merged**
